#!/usr/bin/env python3
"""PostToolUse hook v3: DELEGATE fulfillment + nonce-based skill recording.

Changes from v2:
  - Records Skill tool invocations with session nonce for anti-injection
  - Nonce-stamped files in /tmp/taskmaster/<session>/verified_skills/
  - Prevents transcript marker injection (pkmdev-6v9)

Transitions DELEGATE → FULFILLED only when:
  1. Bash command starts with arbor/arbor-swarm
  2. Command includes --result-file (actual work, not --help)
  3. The command was not a trivial no-op
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

STATE_FILE = (
    Path.home() / ".claude" / "hooks" / ".acontext_state" / "delegate_mode.json"
)
SESSION_LOCK = Path("/tmp/.claude-orchestrator-lock")
READ_BUDGET_FILE = Path("/tmp/.claude-orchestrator-reads")


def _record_skill_invocation(event: dict) -> None:
    """Record a Skill tool invocation with session nonce for verification.

    The nonce is generated by check-completion.sh (stop hook) and stored
    in the session-scoped counter dir.  We read it and write it to a
    skill-specific file.  check-completion.sh then verifies the nonce
    matches instead of grepping the transcript for text markers.
    """
    tool_input = event.get("tool_input", {})
    skill_name = (tool_input.get("skill", "") or "").strip()
    session_id = (event.get("session_id", "") or "").strip()

    if not skill_name or not session_id:
        return

    tmpdir = os.environ.get("TMPDIR", "/tmp")
    counter_dir = Path(tmpdir) / "taskmaster" / session_id
    nonce_file = counter_dir / "verification_nonce"

    if not nonce_file.exists():
        return  # No nonce yet — stop hook hasn't run; record on next invocation

    nonce = nonce_file.read_text(encoding="utf-8").strip()
    if not nonce:
        return

    skill_dir = counter_dir / "verified_skills"
    skill_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / skill_name).write_text(nonce, encoding="utf-8")


def main() -> None:
    try:
        event_json = sys.stdin.read().strip()
        if not event_json:
            return

        event = json.loads(event_json)
        tool_name = event.get("tool_name", "")

        # ── Record Skill invocations for nonce-based verification ──
        if tool_name == "Skill":
            _record_skill_invocation(event)
            return

        if tool_name != "Bash":
            return

        tool_input = event.get("tool_input", {})
        command = (tool_input.get("command", "") or "").strip()

        # Only fulfill when the command is a real arbor/arbor-swarm invocation
        is_real_invocation = (
            (
                command.startswith("arbor")
                or command.startswith("arbor-swarm")
                or "| arbor" in command
                or "| arbor-swarm" in command
            )
            and "--result-file" in command  # Must produce output (not --help)
            and "--help" not in command  # Not a help check
            and "--version" not in command  # Not a version check
        )

        if not is_real_invocation:
            return

        # Read current state
        if not STATE_FILE.exists():
            return

        state = json.loads(STATE_FILE.read_text(encoding="utf-8"))

        if state.get("mode") != "DELEGATE":
            return

        # Transition: DELEGATE → FULFILLED
        import datetime as dt

        state["mode"] = "FULFILLED"
        state["fulfilled_at"] = dt.datetime.now(dt.timezone.utc).isoformat()
        state["fulfilled_command"] = command[:200]
        STATE_FILE.write_text(json.dumps(state), encoding="utf-8")

        # Remove session lock and read budget so post-delegation tools
        # (Read, Grep, etc.) are allowed for reviewing arbor output.
        # Without this, the lock persists for 4h and blocks everything.
        for lock_file in (SESSION_LOCK, READ_BUDGET_FILE):
            try:
                lock_file.unlink(missing_ok=True)
            except OSError:
                pass

    except Exception:
        pass  # PostToolUse hooks should not interfere with tool execution


if __name__ == "__main__":
    main()
